// ─── Decisions Mock Data ────────────────────────────────────────────────────

export type DecisionActor = 'AI' | 'human'
export type DecisionStatus = 'accepted' | 'rejected' | 'modified'

export interface ShapImpact {
  feature: string
  impact: number
}

export interface Decision {
  id: string
  timestamp: string
  actor: DecisionActor
  actorName: string
  actionType: string
  material: string
  before: string
  after: string
  reasoning: string
  shapFeatures: ShapImpact[]
  status: DecisionStatus
}

export const decisionTypes: string[] = [
  'Reorder Trigger',
  'Supplier Switch',
  'Price Lock',
  'Stock Transfer',
  'PO Cancellation',
  'Emergency Purchase',
  'Safety Stock Adjust',
  'Demand Override',
  'Forecast Update',
  'Liquidation',
]

export const decisions: Decision[] = [
  {
    id: 'DEC-001',
    timestamp: '2025-06-19T09:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Reorder Trigger',
    material: 'OPC Cement 53 Grade',
    before: 'Stock: 320 MT (40% of safety stock)',
    after: 'PO Raised: 1500 MT from ACC Cement',
    reasoning: 'Stock critically low. 3 site orders due next week. Pre-monsoon buy. Lead time 7 days.',
    shapFeatures: [
      { feature: 'Stock Level', impact: -0.42 },
      { feature: 'Lead Time', impact: 0.28 },
      { feature: 'Demand Forecast', impact: 0.22 },
      { feature: 'Price Trend', impact: 0.08 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-002',
    timestamp: '2025-06-19T08:45:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Supplier Switch',
    material: 'MS Plates 12mm',
    before: 'Supplier: SAIL (at risk, delayed)',
    after: 'Switch to Tata Steel for next 2 POs',
    reasoning: 'SAIL labor unrest detected. PO delay confirmed. Tata Steel has 900MT available capacity at 3% premium.',
    shapFeatures: [
      { feature: 'Supplier Risk Score', impact: -0.56 },
      { feature: 'Alternate Capacity', impact: 0.38 },
      { feature: 'Price Delta', impact: -0.12 },
      { feature: 'Lead Time', impact: 0.18 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-003',
    timestamp: '2025-06-19T08:20:00Z',
    actor: 'human',
    actorName: 'Priya Sharma',
    actionType: 'Price Lock',
    material: 'TMT Steel Bars 12mm',
    before: 'AI suggested WAIT at ₹58,400/MT',
    after: 'Human override: BUY 500 MT at ₹58,400',
    reasoning: 'Spot price lock-in from Tata Steel valid only today. China tariff news indicates price will rise 4-7%.',
    shapFeatures: [
      { feature: 'Market Intelligence', impact: 0.48 },
      { feature: 'Supplier Offer', impact: 0.32 },
      { feature: 'Budget Availability', impact: 0.20 },
    ],
    status: 'modified',
  },
  {
    id: 'DEC-004',
    timestamp: '2025-06-18T17:30:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Stock Transfer',
    material: 'Copper Wire 6mm',
    before: 'Rajasthan: 2,400 units excess; Gujarat: shortage',
    after: 'Inter-warehouse transfer: RJ→GJ, 1,800 units',
    reasoning: 'Transfer cost ₹2.8L vs fresh procurement ₹38.4L. Net saving ₹35.6L. Transit time 36 hours.',
    shapFeatures: [
      { feature: 'Cost Differential', impact: 0.62 },
      { feature: 'Transit Time', impact: -0.18 },
      { feature: 'Urgency Score', impact: 0.30 },
      { feature: 'Stock Gap', impact: 0.22 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-005',
    timestamp: '2025-06-18T16:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'PO Cancellation',
    material: 'Plywood BWR 18mm',
    before: 'PO/2025/06/012 from Greenply — ₹16L',
    after: 'PO Cancelled. Supplier blacklisted.',
    reasoning: 'Greenply on-time delivery 48.6%. 5th consecutive SLA breach. Risk score 44.2. Procurement halted per policy.',
    shapFeatures: [
      { feature: 'Supplier Score', impact: -0.70 },
      { feature: 'SLA Breach Count', impact: -0.45 },
      { feature: 'Policy Threshold', impact: -0.35 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-006',
    timestamp: '2025-06-18T14:15:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Emergency Purchase',
    material: 'River Sand Grade 2',
    before: 'Zero stock. No active PO.',
    after: 'Emergency PO raised: 5000 MT from 3 vendors',
    reasoning: '4 projects critical path dependent on sand. Estimated delay cost ₹84Cr. Emergency vendor prequalified.',
    shapFeatures: [
      { feature: 'Project Criticality', impact: 0.80 },
      { feature: 'Stock Emergency', impact: -0.90 },
      { feature: 'Cost of Delay', impact: -0.72 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-007',
    timestamp: '2025-06-18T12:00:00Z',
    actor: 'human',
    actorName: 'Rahul Verma',
    actionType: 'Safety Stock Adjust',
    material: 'Diesel HSD',
    before: 'Safety stock: 20,000 L',
    after: 'Safety stock raised to: 30,000 L',
    reasoning: 'Monsoon season + OPEC cuts = supply uncertainty. Manual safety buffer increase approved by warehouse manager.',
    shapFeatures: [
      { feature: 'Seasonal Risk', impact: 0.42 },
      { feature: 'Supply Uncertainty', impact: 0.38 },
      { feature: 'Cost of Stockout', impact: 0.30 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-008',
    timestamp: '2025-06-18T10:30:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Demand Override',
    material: 'Bitumen VG-30',
    before: 'AI forecast: 3,200 MT for Q3',
    after: 'Adjusted forecast: 2,600 MT (monsoon downward correction)',
    reasoning: 'Monsoon road work pause pattern detected in historical data. Q3 state road budget frozen. Demand revised -18.75%.',
    shapFeatures: [
      { feature: 'Monsoon Pattern', impact: -0.52 },
      { feature: 'Budget Signal', impact: -0.38 },
      { feature: 'Historical Pattern', impact: -0.28 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-009',
    timestamp: '2025-06-17T16:45:00Z',
    actor: 'human',
    actorName: 'Deepak Kumar',
    actionType: 'Reorder Trigger',
    material: 'Bitumen VG-30',
    before: 'AI suggested WAIT',
    after: 'Human override: BUY 500 MT immediately',
    reasoning: 'State highway contract signed unexpectedly. Immediate 500 MT need confirmed by project site.',
    shapFeatures: [
      { feature: 'Contract Signal', impact: 0.80 },
      { feature: 'Urgency', impact: 0.60 },
      { feature: 'AI Confidence Override', impact: -0.30 },
    ],
    status: 'modified',
  },
  {
    id: 'DEC-010',
    timestamp: '2025-06-17T14:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Forecast Update',
    material: 'Aluminum Sheets 2mm',
    before: 'Forecast: 420 MT/month',
    after: 'Updated forecast: 520 MT/month (+23.8%)',
    reasoning: 'EV sector aluminum demand surge detected. 3 new client orders confirmed. LME price rise signal.',
    shapFeatures: [
      { feature: 'New Order Signal', impact: 0.58 },
      { feature: 'Market Price Signal', impact: 0.32 },
      { feature: 'Client Inquiry Rate', impact: 0.28 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-011',
    timestamp: '2025-06-17T11:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Liquidation',
    material: 'PVC Conduit 25mm',
    before: 'Stock: 14,200 units (887 days supply)',
    after: 'Liquidation plan: sell 8,000 units at 12% discount',
    reasoning: 'Dead stock risk. 887 days of supply vs 30-day reorder cycle. Capital cost > holding value.',
    shapFeatures: [
      { feature: 'Days of Supply', impact: -0.68 },
      { feature: 'Capital Cost', impact: -0.42 },
      { feature: 'Market Demand', impact: -0.24 },
    ],
    status: 'modified',
  },
  {
    id: 'DEC-012',
    timestamp: '2025-06-17T09:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Reorder Trigger',
    material: 'Copper Cable 16mm²',
    before: 'Stock: 680 units at reorder point',
    after: 'PO raised: 1200 units from Finolex Cables',
    reasoning: 'Client MCB grid expansion confirmed. Demand revised +50%. Reorder quantity increased proportionally.',
    shapFeatures: [
      { feature: 'Demand Signal', impact: 0.64 },
      { feature: 'Client Confirmation', impact: 0.50 },
      { feature: 'Stock Level', impact: -0.28 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-013',
    timestamp: '2025-06-16T15:30:00Z',
    actor: 'human',
    actorName: 'Anita Patel',
    actionType: 'Liquidation',
    material: 'PVC Conduit 25mm',
    before: 'AI: liquidate 8000 units',
    after: 'Human: liquidate 4000 units only',
    reasoning: 'Keeping 4000 unit buffer for potential Bhopal project contingency. Final decision pending project confirmation.',
    shapFeatures: [
      { feature: 'Project Contingency', impact: 0.48 },
      { feature: 'Risk Aversion', impact: 0.30 },
    ],
    status: 'modified',
  },
  {
    id: 'DEC-014',
    timestamp: '2025-06-16T13:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Supplier Switch',
    material: 'PVC Conduit 25mm',
    before: 'Primary: Polyplex Corp (at-risk)',
    after: 'Switch to Supreme Industries as primary',
    reasoning: 'Polyplex score 62.8, 5 consecutive delays. Supreme has 83.8 score and 11-day lead time vs Polyplex 21-day.',
    shapFeatures: [
      { feature: 'Polyplex Risk Score', impact: -0.62 },
      { feature: 'Supreme Capacity', impact: 0.42 },
      { feature: 'Lead Time Improvement', impact: 0.38 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-015',
    timestamp: '2025-06-16T10:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Safety Stock Adjust',
    material: 'TMT Steel Bars 12mm',
    before: 'Safety stock: 1,200 MT',
    after: 'Safety stock raised to: 1,500 MT',
    reasoning: 'China tariff risk + SAIL disruption = supply uncertainty spike. Safety stock increase justified by risk model.',
    shapFeatures: [
      { feature: 'Supply Risk Score', impact: -0.58 },
      { feature: 'Demand Volatility', impact: 0.32 },
      { feature: 'Lead Time Uncertainty', impact: -0.28 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-016',
    timestamp: '2025-06-15T16:00:00Z',
    actor: 'human',
    actorName: 'Suresh Iyer',
    actionType: 'Reorder Trigger',
    material: 'Copper Cable 16mm²',
    before: 'AI suggested 800 units',
    after: 'Human override: 1200 units',
    reasoning: 'MCB grid expansion scope confirmed to be 50% larger than AI estimated. Demand override by site manager.',
    shapFeatures: [
      { feature: 'Site Confirmation', impact: 0.72 },
      { feature: 'Scope Expansion', impact: 0.50 },
    ],
    status: 'modified',
  },
  {
    id: 'DEC-017',
    timestamp: '2025-06-15T11:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Price Lock',
    material: 'Aluminum Sheets 2mm',
    before: 'Spot buying each month',
    after: '3-month forward contract at ₹2,14,500/MT',
    reasoning: 'LME aluminum futures signal 8% increase. Locking at current rate saves estimated ₹3.4Cr over 3 months.',
    shapFeatures: [
      { feature: 'LME Futures Signal', impact: 0.62 },
      { feature: 'Savings Opportunity', impact: 0.48 },
      { feature: 'Hedge Ratio', impact: 0.28 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-018',
    timestamp: '2025-06-14T14:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Demand Override',
    material: 'River Sand Grade 2',
    before: 'Forecast: 0 MT (no demand registered)',
    after: 'Emergency demand: 5000 MT in next 30 days',
    reasoning: 'AI cross-referenced project BOM schedules and detected sand requirement missed in base forecast due to data lag.',
    shapFeatures: [
      { feature: 'BOM Analysis', impact: 0.82 },
      { feature: 'Project Schedule', impact: 0.68 },
      { feature: 'Data Gap Detection', impact: 0.44 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-019',
    timestamp: '2025-06-14T10:30:00Z',
    actor: 'human',
    actorName: 'Meera Nair',
    actionType: 'Reorder Trigger',
    material: 'Diesel HSD',
    before: 'AI: BUY — fill tanks now',
    after: 'Human: WAIT 24 hours for bulk deal',
    reasoning: 'Petrol bunk negotiation in progress. Expecting bulk discount of ₹0.8/L. Decision: wait one day.',
    shapFeatures: [
      { feature: 'Negotiation Signal', impact: 0.40 },
      { feature: 'Urgency Level', impact: -0.28 },
    ],
    status: 'rejected',
  },
  {
    id: 'DEC-020',
    timestamp: '2025-06-13T16:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Forecast Update',
    material: 'OPC Cement 53 Grade',
    before: 'Forecast MAPE: 4.2%',
    after: 'Model retrained. MAPE improved to 5.8% (degraded — drift detected)',
    reasoning: 'Drift score exceeded 0.75 threshold. Auto-retraining triggered. New dataset incorporates Q2 2025 actuals.',
    shapFeatures: [
      { feature: 'Drift Score', impact: -0.70 },
      { feature: 'Data Freshness', impact: 0.45 },
      { feature: 'MAPE Threshold', impact: -0.38 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-021',
    timestamp: '2025-06-13T11:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Stock Transfer',
    material: 'Plywood BWR 18mm',
    before: 'Mumbai: 2200 sheets excess',
    after: 'Transfer 2200 sheets to Mumbai for active use',
    reasoning: 'Mumbai site active usage detected. Inter-hub transfer avoids ₹8.8L liquidation cost.',
    shapFeatures: [
      { feature: 'Site Usage Signal', impact: 0.60 },
      { feature: 'Cost Avoidance', impact: 0.50 },
      { feature: 'Transfer Feasibility', impact: 0.32 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-022',
    timestamp: '2025-06-12T14:00:00Z',
    actor: 'human',
    actorName: 'Kavita Singh',
    actionType: 'Safety Stock Adjust',
    material: 'Aluminum Sheets 2mm',
    before: 'AI: reduce safety stock to 300 MT',
    after: 'Human: keep at 400 MT',
    reasoning: 'Aerospace client visit next week. Keeping stock as demo inventory. Safety stock unchanged.',
    shapFeatures: [
      { feature: 'Business Development', impact: 0.52 },
      { feature: 'Risk Aversion', impact: 0.28 },
    ],
    status: 'rejected',
  },
  {
    id: 'DEC-023',
    timestamp: '2025-06-12T10:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Reorder Trigger',
    material: 'HDPE Pipes 110mm',
    before: 'Stock: 920 units (above reorder point)',
    after: 'No action required. Monitoring.',
    reasoning: 'Stock adequate for next 28 days. Demand forecast stable. No action needed.',
    shapFeatures: [
      { feature: 'Stock Adequacy', impact: 0.68 },
      { feature: 'Demand Stability', impact: 0.42 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-024',
    timestamp: '2025-06-11T15:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'PO Cancellation',
    material: 'Rubber Gaskets 10"',
    before: 'PO pending for 800 units',
    after: 'PO cancelled. Demand forecasted at zero.',
    reasoning: 'Project using rubber gaskets was cancelled by client. BOM dependency removed. Zero demand confirmed.',
    shapFeatures: [
      { feature: 'Project Cancellation', impact: -0.88 },
      { feature: 'BOM Dependency', impact: -0.60 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-025',
    timestamp: '2025-06-11T10:00:00Z',
    actor: 'human',
    actorName: 'Arun Gupta',
    actionType: 'Emergency Purchase',
    material: 'River Sand Grade 2',
    before: 'AI emergency PO suggestion',
    after: 'Emergency PO accepted. CFO approval granted.',
    reasoning: 'Accepted AI recommendation. CFO approved emergency procurement. 3 vendors contacted.',
    shapFeatures: [
      { feature: 'Emergency Trigger', impact: 0.90 },
      { feature: 'CFO Approval', impact: 0.80 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-026',
    timestamp: '2025-06-10T14:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Demand Override',
    material: 'Glass Wool Insulation',
    before: 'Forecast: 50 units/month',
    after: 'Forecast revised to 0 (dead stock material)',
    reasoning: 'No consumption in 92 days. Project types not using insulation. Demand set to zero.',
    shapFeatures: [
      { feature: 'Consumption History', impact: -0.80 },
      { feature: 'Project Portfolio', impact: -0.50 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-027',
    timestamp: '2025-06-10T10:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Forecast Update',
    material: 'Bitumen VG-30',
    before: 'Q3 forecast: 3,200 MT',
    after: 'Q3 forecast revised: 2,600 MT (-18.75%)',
    reasoning: 'Monsoon road work pause + frozen state budget = lower bitumen demand Q3. Historical monsoon pattern applied.',
    shapFeatures: [
      { feature: 'Monsoon Factor', impact: -0.56 },
      { feature: 'Budget Freeze', impact: -0.42 },
      { feature: 'Historical Seasonality', impact: -0.32 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-028',
    timestamp: '2025-06-09T15:00:00Z',
    actor: 'human',
    actorName: 'Sana Khan',
    actionType: 'Stock Transfer',
    material: 'Plywood BWR 18mm',
    before: 'AI: liquidate excess stock',
    after: 'Human: transfer to Mumbai instead',
    reasoning: 'Mumbai site has active use for excess plywood. Transfer more economical than liquidation.',
    shapFeatures: [
      { feature: 'Site Demand', impact: 0.64 },
      { feature: 'Transfer Cost', impact: -0.22 },
    ],
    status: 'modified',
  },
  {
    id: 'DEC-029',
    timestamp: '2025-06-09T10:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Reorder Trigger',
    material: 'Angle Steel 50x50',
    before: 'Stock: 1650 MT (above safety stock)',
    after: 'PO raised: 500 MT (scheduled, not emergency)',
    reasoning: 'Reorder point triggered per replenishment plan. Lead time 12 days. Maintaining buffer ahead of Q3 projects.',
    shapFeatures: [
      { feature: 'Reorder Point', impact: -0.38 },
      { feature: 'Lead Time', impact: 0.28 },
      { feature: 'Q3 Demand Signal', impact: 0.32 },
    ],
    status: 'accepted',
  },
  {
    id: 'DEC-030',
    timestamp: '2025-06-08T14:00:00Z',
    actor: 'AI',
    actorName: 'SupplySense AI',
    actionType: 'Price Lock',
    material: 'Diesel HSD',
    before: 'Spot fuel purchase each week',
    after: 'Bulk contract: 100,000L/month at ₹89.62/L for 3 months',
    reasoning: 'OPEC production cut extension signal. Locking in current diesel price for 3 months saves estimated ₹4.8L.',
    shapFeatures: [
      { feature: 'OPEC Signal', impact: -0.52 },
      { feature: 'Savings Potential', impact: 0.44 },
      { feature: 'Volume Discount', impact: 0.30 },
    ],
    status: 'accepted',
  },
]
