"""
SupplySense API - Risk SQLAlchemy Models
RiskEvents, Alerts, MonteCarloRuns
"""

from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from core.database import Base


class RiskEvent(Base):
    """
    Supply chain risk event with probability, impact, and lifecycle tracking.
    """

    __tablename__ = "risk_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    category: Mapped[str] = mapped_column(
        Enum(
            "geopolitical",
            "natural_disaster",
            "supplier_financial",
            "cybersecurity",
            "regulatory",
            "logistics",
            "demand_shock",
            "quality",
            "labor",
            "currency",
            name="risk_category",
        ),
        nullable=False,
        index=True,
    )
    source: Mapped[str] = mapped_column(
        Enum("ai_detected", "manual", "news_feed", "supplier_alert", name="risk_source"),
        default="manual",
        nullable=False,
    )
    probability: Mapped[float] = mapped_column(Float, nullable=False)  # 0.0 – 1.0
    impact_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    severity: Mapped[str] = mapped_column(
        Enum("critical", "high", "medium", "low", name="risk_severity"),
        nullable=False,
        index=True,
    )
    status: Mapped[str] = mapped_column(
        Enum("active", "monitoring", "mitigated", "closed", name="risk_status"),
        default="active",
        nullable=False,
        index=True,
    )
    affected_suppliers: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON list of supplier IDs
    affected_skus: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON list
    affected_regions: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON list
    mitigation_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    mitigation_status: Mapped[str | None] = mapped_column(String(100), nullable=True)
    owner_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    start_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    end_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    news_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    tags: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    @property
    def risk_score(self) -> float:
        """Composite risk score = probability × impact (normalized)."""
        return round(self.probability * min(self.impact_usd / 1_000_000, 10), 2)

    def __repr__(self) -> str:
        return f"<RiskEvent title={self.title} severity={self.severity} status={self.status}>"


class Alert(Base):
    """
    Real-time supply chain alert generated by AI agents or rule engines.
    """

    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    alert_type: Mapped[str] = mapped_column(
        Enum(
            "stock_critical",
            "stock_low",
            "overstock",
            "supplier_risk",
            "delivery_delay",
            "price_spike",
            "demand_surge",
            "quality_issue",
            "contract_expiry",
            "forecast_deviation",
            "agent_action",
            "system",
            name="alert_type",
        ),
        nullable=False,
        index=True,
    )
    severity: Mapped[str] = mapped_column(
        Enum("critical", "high", "medium", "low", "info", name="alert_severity"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(String(100), nullable=False)  # agent name or system
    resource_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    resource_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    metadata_json: Mapped[str | None] = mapped_column(Text, nullable=True)  # extra context
    acknowledged: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    acknowledged_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    auto_resolve: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    notification_sent: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )

    def __repr__(self) -> str:
        return f"<Alert type={self.alert_type} severity={self.severity} acked={self.acknowledged}>"


class MonteCarloRun(Base):
    """
    Monte Carlo simulation run for supply chain risk quantification.
    """

    __tablename__ = "monte_carlo_runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    simulation_name: Mapped[str] = mapped_column(String(255), nullable=False)
    iterations: Mapped[int] = mapped_column(Integer, nullable=False, default=10000)
    horizon_days: Mapped[int] = mapped_column(Integer, nullable=False, default=90)
    parameters: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON

    # Results
    p10_impact: Mapped[float | None] = mapped_column(Float, nullable=True)
    p50_impact: Mapped[float | None] = mapped_column(Float, nullable=True)
    p90_impact: Mapped[float | None] = mapped_column(Float, nullable=True)
    expected_impact: Mapped[float | None] = mapped_column(Float, nullable=True)
    max_impact: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_of_disruption: Mapped[float | None] = mapped_column(Float, nullable=True)
    results_json: Mapped[str | None] = mapped_column(Text, nullable=True)  # Full histogram data

    status: Mapped[str] = mapped_column(
        Enum("running", "completed", "failed", name="sim_status"),
        default="running",
        nullable=False,
    )
    duration_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    triggered_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    def __repr__(self) -> str:
        return f"<MonteCarloRun name={self.simulation_name} status={self.status}>"
